package pwm.penna.pojo.dipendente;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Time;

import pwm.penna.pojo.cassiere.Cassiere;
import pwm.penna.pojo.dirigente.Dirigente;
import pwm.penna.pojo.profilo.Profilo;
import pwm.penna.pojo.tecnico.Tecnico;

/**
 * Dipendente generated by hbm2java
 */
public class Dipendente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer idDipendente;
	private Profilo profilo;
	private BigDecimal salario;
	private Time inizioTurno;
	private Time fineTurno;

	public Dipendente() {
	}

	public Dipendente(Profilo profilo, BigDecimal salario, Time inizioTurno, Time fineTurno) {
		this.profilo = profilo;
		this.salario = salario;
		this.inizioTurno = inizioTurno;
		this.fineTurno = fineTurno;
	}

	public Integer getIdDipendente() {
		return idDipendente;
	}

	public void setIdDipendente(Integer idDipendente) {
		this.idDipendente = idDipendente;
	}

	public BigDecimal getSalario() {
		return salario;
	}

	public void setSalario(BigDecimal salario) {
		this.salario = salario;
	}

	public Time getInizioTurno() {
		return inizioTurno;
	}

	public void setInizioTurno(Time inizioTurno) {
		this.inizioTurno = inizioTurno;
	}

	public Time getFineTurno() {
		return fineTurno;
	}

	public void setFineTurno(Time fineTurno) {
		this.fineTurno = fineTurno;
	}

	public Profilo getProfilo() {
		return profilo;
	}

	public void setProfilo(Profilo profilo) {
		this.profilo = profilo;
	}
	
	public boolean isTecnico() {
		return this instanceof Tecnico;
	}
	
	public boolean isCassiere() {
		return this instanceof Cassiere;
	}
	
	public boolean isDirigente() {
		return this instanceof Dirigente;
	}
}
