package pwm.penna.pojo.cliente;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.richiede.Richiede;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer numeroCliente;
	private Set<Richiede> richieste = new HashSet<>();

	public Cliente() {
	}

	public Cliente(Set<Richiede> richieste) {
		this.richieste = richieste;
	}

	public Integer getNumeroCliente() {
		return this.numeroCliente;
	}

	public void setNumeroCliente(Integer numeroCliente) {
		this.numeroCliente = numeroCliente;
	}

	public Set<Richiede> getRichieste() {
		return this.richieste;
	}

	public void setRichieste(Set<Richiede> richieste) {
		this.richieste = richieste;
	}

}
