package pwm.penna.pojo.assegna;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Time;

import pwm.penna.pojo.cassiere.Cassiere;
import pwm.penna.pojo.richiede.Richiede;


/**
 * Assegna generated by hbm2java
 */
public class Assegna implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer prenotazione;
	private Cassiere cassiere;
	private Richiede richiede;
	private BigDecimal costo;
	private Time orario;

	public Assegna() {
	}

	public Assegna(Cassiere cassiere, BigDecimal costo, Time orario) {
		this.cassiere = cassiere;
		this.costo = costo;
		this.orario = orario;
	}

	public Integer getPrenotazione() {
		return this.prenotazione;
	}

	public void setPrenotazione(Integer prenotazione) {
		this.prenotazione = prenotazione;
	}

	public Cassiere getCassiere() {
		return this.cassiere;
	}

	public void setCassiere(Cassiere cassiere) {
		this.cassiere = cassiere;
	}

	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	public Time getOrario() {
		return this.orario;
	}

	public void setOrario(Time orario) {
		this.orario = orario;
	}

	public Richiede getRichiede() {
		return richiede;
	}

	public void setRichiede(Richiede richiede) {
		this.richiede = richiede;
	}

}
