package pwm.penna.pojo.tecnico;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.dipendente.Dipendente;
import pwm.penna.pojo.ripara.Ripara;

/**
 * Tecnico generated by hbm2java
 */
public class Tecnico extends Dipendente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String specializzazione;
	private Set<Ripara> riparazioni = new HashSet<>();

	public Tecnico() {
	}

	public Tecnico(String specializzazione) {
		this.specializzazione = specializzazione;
	}

	public Tecnico(String specializzazione, Set<Ripara> riparazioni) {
		this.specializzazione = specializzazione;
		this.riparazioni = riparazioni;
	}

	public String getSpecializzazione() {
		return specializzazione;
	}

	public void setSpecializzazione(String specializzazione) {
		this.specializzazione = specializzazione;
	}

	public Set<Ripara> getRiparazioni() {
		return riparazioni;
	}

	public void setRiparazioni(Set<Ripara> riparazioni) {
		this.riparazioni = riparazioni;
	}
}
