package pwm.penna.pojo.socio;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import pwm.penna.pojo.cliente.Cliente;
import pwm.penna.pojo.profilo.Profilo;

/**
 * Socio generated by hbm2java
 */
public class Socio implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer numeroCliente;
	private Cliente cliente;
	private Profilo profilo;
	private int punteggio;
	private Date membroDal;

	public Socio() {
	}

	public Socio(Cliente cliente, Profilo profilo, int punteggio, Date membroDal) {
		this.cliente = cliente;
		this.profilo = profilo;
		this.punteggio = punteggio;
		this.membroDal = membroDal;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Profilo getProfilo() {
		return this.profilo;
	}

	public void setProfilo(Profilo profilo) {
		this.profilo = profilo;
	}

	public int getPunteggio() {
		return this.punteggio;
	}

	public void setPunteggio(int punteggio) {
		this.punteggio = punteggio;
	}

	public Date getMembroDal() {
		return this.membroDal;
	}

	public void setMembroDal(Date membroDal) {
		this.membroDal = membroDal;
	}

	public Integer getNumeroCliente() {
		return numeroCliente;
	}

	public void setNumeroCliente(Integer numeroCliente) {
		this.numeroCliente = numeroCliente;
	}
}
