package pwm.penna.pojo.dispositivodigioco;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.dispositivodigioco.tipo.PC;
import pwm.penna.pojo.dispositivodigioco.tipo.PlayStation;
import pwm.penna.pojo.dispositivodigioco.tipo.Xbox;
import pwm.penna.pojo.postazione.Postazione;
import pwm.penna.pojo.ripara.Ripara;

/**
 * DispositivoDiGioco generated by hbm2java
 */
public class DispositivoDiGioco implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Date dataAcquisizione;
	private Postazione postazione;
	private Set<Ripara> riparazioni = new HashSet<>();

	public DispositivoDiGioco() {
	}

	public DispositivoDiGioco(Date dataAcquisizione) {
		this.dataAcquisizione = dataAcquisizione;
	}
	
	public DispositivoDiGioco(Integer id, Date dataAcquisizione) {
		this.id = id;
		this.dataAcquisizione = dataAcquisizione;
	}

	public DispositivoDiGioco(Date dataAcquisizione, Postazione postazione, Set<Ripara> riparazioni) {
		this.dataAcquisizione = dataAcquisizione;
		this.postazione = postazione;
		this.riparazioni = riparazioni;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDataAcquisizione() {
		return this.dataAcquisizione;
	}

	public void setDataAcquisizione(Date dataAcquisizione) {
		this.dataAcquisizione = dataAcquisizione;
	}
	
	public Postazione getPostazione() {
		return postazione;
	}

	public void setPostazione(Postazione postazione) {
		this.postazione = postazione;
	}

	public Set<Ripara> getRiparazioni() {
		return this.riparazioni;
	}

	public void setRiparazioni(Set<Ripara> riparazioni) {
		this.riparazioni = riparazioni;
	}

	public String getTipo() {
		if(this instanceof PC) return PC.DISCRIMINATOR;
		if(this instanceof Xbox) return Xbox.DISCRIMINATOR;
		if(this instanceof PlayStation) return PlayStation.DISCRIMINATOR;
		return null;
	}
}
