package pwm.penna.pojo.dirigente;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.dipendente.Dipendente;
import pwm.penna.pojo.salagiochi.SalaGiochi;

/**
 * Dirigente generated by hbm2java
 */
public class Dirigente extends Dipendente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer esperienza;
	private Integer periodo;
	private Set<SalaGiochi> sale = new HashSet<>();

	public Dirigente() {
	}

	public Dirigente(Integer esperienza, Integer periodo) {
		this.esperienza = esperienza;
		this.periodo = periodo;
	}

	public Dirigente(Integer esperienza, Integer periodo, Set<SalaGiochi> sale) {
		this.esperienza = esperienza;
		this.periodo = periodo;
		this.sale = sale;
	}

	public int getEsperienza() {
		return esperienza;
	}

	public void setEsperienza(Integer esperienza) {
		this.esperienza = esperienza;
	}

	public Integer getPeriodo() {
		return periodo;
	}

	public void setPeriodo(Integer periodo) {
		this.periodo = periodo;
	}

	public Set<SalaGiochi> getSale() {
		return sale;
	}

	public void setSale(Set<SalaGiochi> sale) {
		this.sale = sale;
	}
}
