package pwm.penna.pojo.cassiere;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.assegna.Assegna;
import pwm.penna.pojo.dipendente.Dipendente;
import pwm.penna.pojo.salagiochi.SalaGiochi;

/**
 * Cassiere generated by hbm2java
 */
public class Cassiere extends Dipendente implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer sportello;
	private SalaGiochi salaGiochi;
	private Set<Assegna> assegnazioni = new HashSet<>();

	public Cassiere() {
	}

	public Cassiere(Integer sportello, SalaGiochi salaGiochi) {
		this.sportello = sportello;
		this.salaGiochi = salaGiochi;
	}

	public Cassiere(Integer sportello, SalaGiochi salaGiochi, Set<Assegna> assegnazioni) {
		this.sportello = sportello;
		this.salaGiochi = salaGiochi;
		this.assegnazioni = assegnazioni;
	}

	public Integer getSportello() {
		return sportello;
	}

	public void setSportello(Integer sportello) {
		this.sportello = sportello;
	}

	public Set<Assegna> getAssegnazioni() {
		return assegnazioni;
	}

	public void setAssegnazioni(Set<Assegna> assegnazioni) {
		this.assegnazioni = assegnazioni;
	}

	public SalaGiochi getSalaGiochi() {
		return salaGiochi;
	}

	public void setSalaGiochi(SalaGiochi salaGiochi) {
		this.salaGiochi = salaGiochi;
	}
}
