package pwm.penna.pojo.profilo;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import pwm.penna.pojo.account.Account;
import pwm.penna.pojo.dipendente.Dipendente;
import pwm.penna.pojo.socio.Socio;

/**
 * Profilo generated by hbm2java
 */
public class Profilo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String email;
	private Account account;
	private String nome;
	private String cognome;
	private String sesso;
	private Date dataDiNascita;
	private String codiceFiscale;
	private long telefono;
	private String via;
	private int numeroCivico;
	private String citta;
	private int cap;
	private Socio socio;
	private Dipendente dipendente;

	public Profilo() {
	}

	public Profilo(Account account, String nome, String cognome, String sesso,
			Date dataDiNascita, String codiceFiscale, long telefono, String via, int numeroCivico, String citta, int cap) {
		this.account = account;
		this.nome = nome;
		this.cognome = cognome;
		this.sesso = sesso;
		this.dataDiNascita = dataDiNascita;
		this.codiceFiscale = codiceFiscale;
		this.telefono = telefono;
		this.via = via;
		this.numeroCivico = numeroCivico;
		this.citta = citta;
		this.cap = cap;
	}

	public Profilo(Account account, String nome, String cognome, String sesso,
			Date dataDiNascita, String codiceFiscale, long telefono, String via, int numeroCivico, String citta, int cap, Socio socio, Dipendente dipendente) {
		this.account = account;
		this.nome = nome;
		this.cognome = cognome;
		this.sesso = sesso;
		this.dataDiNascita = dataDiNascita;
		this.codiceFiscale = codiceFiscale;
		this.telefono = telefono;
		this.via = via;
		this.numeroCivico = numeroCivico;
		this.citta = citta;
		this.cap = cap;
		this.socio = socio;
		this.dipendente = dipendente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getSesso() {
		return this.sesso;
	}

	public void setSesso(String sesso) {
		this.sesso = sesso;
	}

	public Date getDataDiNascita() {
		return this.dataDiNascita;
	}

	public void setDataDiNascita(Date dataDiNascita) {
		this.dataDiNascita = dataDiNascita;
	}

	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	public long getTelefono() {
		return telefono;
	}

	public void setTelefono(long telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	public int getNumeroCivico() {
		return this.numeroCivico;
	}

	public void setNumeroCivico(int numeroCivico) {
		this.numeroCivico = numeroCivico;
	}

	public String getCitta() {
		return citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public int getCap() {
		return this.cap;
	}

	public void setCap(int cap) {
		this.cap = cap;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Socio getSocio() {
		return socio;
	}

	public void setSocio(Socio socio) {
		this.socio = socio;
	}

	public Dipendente getDipendente() {
		return dipendente;
	}

	public void setDipendente(Dipendente dipendente) {
		this.dipendente = dipendente;
	}
}
