package pwm.penna.pojo.richiede;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.sql.Time;

import pwm.penna.pojo.assegna.Assegna;
import pwm.penna.pojo.cliente.Cliente;
import pwm.penna.pojo.postazione.Postazione;

/**
 * Richiede generated by hbm2java
 */
public class Richiede implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer prenotazione;
	private Cliente cliente;
	private Postazione postazione;
	private Time durata;
	private Assegna assegnazione;

	public Richiede() {
	}

	public Richiede(Cliente cliente, Postazione postazione, Time durata) {
		this.cliente = cliente;
		this.postazione = postazione;
		this.durata = durata;
	}

	public Integer getPrenotazione() {
		return this.prenotazione;
	}

	public void setPrenotazione(Integer prenotazione) {
		this.prenotazione = prenotazione;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Postazione getPostazione() {
		return this.postazione;
	}

	public void setPostazione(Postazione postazione) {
		this.postazione = postazione;
	}

	public Time getDurata() {
		return this.durata;
	}

	public void setDurata(Time durata) {
		this.durata = durata;
	}

	public Assegna getAssegnazione() {
		return assegnazione;
	}

	public void setAssegnazione(Assegna assegnazione) {
		this.assegnazione = assegnazione;
	}

}
