package pwm.penna.pojo.salagiochi;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.sql.Time;
import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.dirigente.Dirigente;
import pwm.penna.pojo.postazione.Postazione;

/**
 * SalaGiochi generated by hbm2java
 */
public class SalaGiochi implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer codice;
	private String nome;
	private int capienza;
	private Time orarioApertura;
	private Time orarioChiusura;
	private Indirizzo indirizzo;
	private Set<Dirigente> dirigenti = new HashSet<>();
	private Set<Postazione> postazioni = new HashSet<>();

	public SalaGiochi() {
	}

	public SalaGiochi(String nome, int capienza, Time orarioApertura, Time orarioChiusura, Indirizzo indirizzo) {
		this.nome = nome;
		this.capienza = capienza;
		this.orarioApertura = orarioApertura;
		this.orarioChiusura = orarioChiusura;
		this.indirizzo = indirizzo;
	}

	public SalaGiochi(String nome, int capienza, Time orarioApertura, Time orarioChiusura, Indirizzo indirizzo, Set<Dirigente> dirigenti, Set<Postazione> postazioni) {
		this.nome = nome;
		this.capienza = capienza;
		this.orarioApertura = orarioApertura;
		this.orarioChiusura = orarioChiusura;
		this.indirizzo = indirizzo;
		this.dirigenti = dirigenti;
		this.postazioni = postazioni;
	}

	public Integer getCodice() {
		return this.codice;
	}

	public void setCodice(Integer codice) {
		this.codice = codice;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public int getCapienza() {
		return this.capienza;
	}

	public void setCapienza(int capienza) {
		this.capienza = capienza;
	}

	public Time getOrarioApertura() {
		return this.orarioApertura;
	}

	public void setOrarioApertura(Time orarioApertura) {
		this.orarioApertura = orarioApertura;
	}

	public Time getOrarioChiusura() {
		return this.orarioChiusura;
	}

	public void setOrarioChiusura(Time orarioChiusura) {
		this.orarioChiusura = orarioChiusura;
	}

	public Set<Dirigente> getDirigenti() {
		return this.dirigenti;
	}

	public void setDirigenti(Set<Dirigente> dirigenti) {
		this.dirigenti = dirigenti;
	}

	public Set<Postazione> getPostazioni() {
		return this.postazioni;
	}

	public void setPostazioni(Set<Postazione> postazioni) {
		this.postazioni = postazioni;
	}

	public Indirizzo getIndirizzo() {
		return indirizzo;
	}

	public void setIndirizzo(Indirizzo indirizzo) {
		this.indirizzo = indirizzo;
	}
}