package pwm.penna.pojo.postazione;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import pwm.penna.pojo.richiede.Richiede;
import pwm.penna.pojo.salagiochi.SalaGiochi;
import pwm.penna.pojo.dispositivodigioco.DispositivoDiGioco;

/**
 * Postazione generated by hbm2java
 */
public class Postazione implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int numero;
	private PostazioneId id;
	private DispositivoDiGioco dispositivoDiGioco;
	private SalaGiochi salaGiochi;
	private Set<Richiede> richieste = new HashSet<>();

	public Postazione() {
	}


	public Postazione(PostazioneId id, DispositivoDiGioco dispositivoDiGioco, SalaGiochi salaGiochi, int numero) {
		this.id = id;
		this.dispositivoDiGioco = dispositivoDiGioco;
		this.salaGiochi = salaGiochi;
		this.numero = numero;
	}

	public Postazione(PostazioneId id, DispositivoDiGioco dispositivoDiGioco, SalaGiochi salaGiochi, int numero,
			Set<Richiede> richieste) {
		this.id = id;
		this.dispositivoDiGioco = dispositivoDiGioco;
		this.salaGiochi = salaGiochi;
		this.numero = numero;
		this.richieste = richieste;
	}

	public DispositivoDiGioco getDispositivoDiGioco() {
		return this.dispositivoDiGioco;
	}

	public void setDispositivoDiGioco(DispositivoDiGioco dispositivoDiGioco) {
		this.dispositivoDiGioco = dispositivoDiGioco;
	}

	public SalaGiochi getSalaGiochi() {
		return this.salaGiochi;
	}

	public void setSalaGiochi(SalaGiochi salaGiochi) {
		this.salaGiochi = salaGiochi;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public Set<Richiede> getRichieste() {
		return this.richieste;
	}

	public void setRichieste(Set<Richiede> richieste) {
		this.richieste = richieste;
	}

	public PostazioneId getId() {
		return id;
	}

	public void setId(PostazioneId id) {
		this.id = id;
	}

}
