package pwm.penna.pojo.postazione;
// Generated 20 dic 2024, 01:47:20 by Hibernate Tools 6.5.1.Final

/**
 * PostazioneId generated by hbm2java
 */
public class PostazioneId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int codiceSalaGiochi;
	private int posto;
	private int stanza;

	public PostazioneId() {
	}

	public PostazioneId(int codiceSalaGiochi, int posto, int stanza) {
		this.codiceSalaGiochi = codiceSalaGiochi;
		this.posto = posto;
		this.stanza = stanza;
	}

	public int getCodiceSalaGiochi() {
		return codiceSalaGiochi;
	}

	public void setCodiceSalaGiochi(int codiceSalaGiochi) {
		this.codiceSalaGiochi = codiceSalaGiochi;
	}

	public int getPosto() {
		return posto;
	}

	public void setPosto(int posto) {
		this.posto = posto;
	}

	public int getStanza() {
		return stanza;
	}

	public void setStanza(int stanza) {
		this.stanza = stanza;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PostazioneId))
			return false;
		PostazioneId castOther = (PostazioneId) other;

		return (this.getCodiceSalaGiochi() == castOther.getCodiceSalaGiochi())
				&& (this.getPosto() == castOther.getPosto()) && (this.getStanza() == castOther.getStanza());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodiceSalaGiochi();
		result = 37 * result + this.getPosto();
		result = 37 * result + this.getStanza();
		return result;
	}

}
