package pwm.penna.pojo.account;
// Generated 23 dic 2024, 15:04:08 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import pwm.penna.pojo.profilo.Profilo;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String email;
	private String password;
	private Date ultimoLogin;
	private Profilo profilo;

	public Account() {
	}

	public Account(String email) {
		this.email = email;
	}

	public Account(String email, String password, Date ultimoLogin, Profilo profilo) {
		this.email = email;
		this.password = password;
		this.ultimoLogin = ultimoLogin;
		this.profilo = profilo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getUltimoLogin() {
		return this.ultimoLogin;
	}

	public void setUltimoLogin(Date ultimoLogin) {
		this.ultimoLogin = ultimoLogin;
	}

	public Profilo getProfilo() {
		return this.profilo;
	}

	public void setProfilo(Profilo profilo) {
		this.profilo = profilo;
	}
	
	public static Account fromProfilo(Profilo p, String pass) {
		return new Account(p.getEmail(), pass, new Date(System.currentTimeMillis()), p);
	}

	public static Account fromProfilo(Profilo p) {
		return fromProfilo(p, null);
	}
}
