package pwm.penna.pojo.ripara;
// Generated 30 nov 2024, 18:01:17 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;

import pwm.penna.pojo.tecnico.Tecnico;
import pwm.penna.pojo.dispositivodigioco.DispositivoDiGioco;

/**
 * Ripara generated by hbm2java
 */
public class Ripara implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer progressivo;
	private DispositivoDiGioco dispositivoDiGioco;
	private Tecnico tecnico;
	private BigDecimal costoRiparazione;

	public Ripara() {
	}

	public Ripara(Integer progressivo, DispositivoDiGioco dispositivoDiGioco, Tecnico tecnico, BigDecimal costoRiparazione) {
		this.progressivo = progressivo;
		this.dispositivoDiGioco = dispositivoDiGioco;
		this.tecnico = tecnico;
		this.costoRiparazione = costoRiparazione;
	}

	public Integer getProgressivo() {
		return this.progressivo;
	}

	public void setProgressivo(Integer progressivo) {
		this.progressivo = progressivo;
	}

	public DispositivoDiGioco getDispositivoDiGioco() {
		return this.dispositivoDiGioco;
	}

	public void setDispositivoDiGioco(DispositivoDiGioco dispositivoDiGioco) {
		this.dispositivoDiGioco = dispositivoDiGioco;
	}

	public Tecnico getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(Tecnico tecnico) {
		this.tecnico = tecnico;
	}

	public BigDecimal getCostoRiparazione() {
		return this.costoRiparazione;
	}

	public void setCostoRiparazione(BigDecimal costoRiparazione) {
		this.costoRiparazione = costoRiparazione;
	}

}
